### ISSUE TITLE
Implement Efron deconvolution for heteroscedastic Normal errors

### ISSUE THREAD

**Issue by maximerischard** [maximerischard/DeconvolutionTests.jl#1]

**Comment by lfcampos** [comment]
I found a deconvolution for Heteroskedastic errors paper:
       Delaigle, A., & Meister, A. (2008). Density estimation with heteroscedastic error. 
       Bernoulli, 14(2), 562–579. http://doi.org/10.3150/08-BEJ121
They have a full implementation in Matlab and R. I tested the R implementation  -- they're essentially doing Kernel Estimator, same as all the other ones so it's very slow. I think the Efron implementation is still worth pursuing, but I wanted to add this here for record-keeping.

**Comment by lfcampos** [comment]
The Implementation is [here](http://researchers.ms.unimelb.edu.au/~aurored/links.html#Code)

**Comment by maximerischard** [comment]
Efron with heteroscedastic errors is now supported by [DeconvolveDistribution.jl](https://github.com/maximerischard/DeconvolveDistribution.jl/commit/f3d61e6e9280546715cdd8deb0b0b1a64d4ff229).

**Comment by maximerischard** [comment]
The Delaigle and Meister paper is also what the R `decon` paper is largely based on.
