### ISSUE TITLE
Deconvolution Test vs KS test

### ISSUE THREAD

**Issue by lfcampos** [maximerischard/DeconvolutionTests.jl#10]
Let's look at a situation where we have a standard test (in this case k.s. test) to compare our deconvolution `decon.test()` to it. This simulation is built to give assurance that in a situation where we know what to do, the deconvolution test does as good (if not better) than the standard test.

Assuming homoskedastic errors, the KS test is valid, the distributions of Y are the same under both groups. For the DGM

Y_i1\~N(mu1, sigma1)  + N(0, sigma^2)
Y_i2\~N(mu2, sigma2)  + N(0, sigma^2)

- `ks({Y_i1}, {Y_i2})` should have a rejection of 5% when mu1=mu2 and sigma1=sigma2.
- `decon.test({Y_i1}, {Y_i2})` should also have this. 

But as we move into the alternative, i.e. mu1<mu2, keeping sigma1=sigma2, both tests will begin to reject H0 more often, eventually leading to 100% power when the separation between mu1, mu2 is large enough (relative to sigma1=sigma2 AND sigma). 

It would be good to see a power profile for increasing separation for varying levels of noise sigma1=sigma2 as well as error noise sigma. 

This can easily get out of hand, even running MLEs (like in my simple example) takes ~20 minutes to get smooth power profiles (2000 replicates). So this may have to wait until [Issue 8](https://github.com/maximerischard/DeconvolutionTests.jl/issues/8) is resolved.

**Comment by maximerischard** [comment]
I had some time to do this yesterday and ran some simulations overnight. The results are in the Homoscedastic_Comparison notebook, which is best viewed with the [jupyter notebook viewer](https://nbviewer.jupyter.org/github/maximerischard/DeconvolutionTests.jl/blob/master/notebooks/Homoscedastic_Comparison.ipynb) (the github preview is a bit shit).
